[package]
name = "bip300301_enforcer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
bitcoin = { version = "0.31.1", features = ["serde"] }
byteorder = "1.5.0"
miette = { version = "7.1.0", features = ["fancy"] }
nom = "7.1.3"
prost = "0.12.3"
heed = { git = "https://github.com/meilisearch/heed", tag = "v0.12.4", version = "0.12.4" }
serde = { version = "1.0.197", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
tonic = "0.11.0"

enforcer_proto = { path = "../enforcer_proto" }
